# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ILIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('Id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_projet', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Type', models.IntegerField(choices=[(0, 'Enseignement'), (1, 'Recherche'), (2, 'Service à la societé')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('Id_fichier', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('Type', models.TextField(blank=True)),
                ('Date_publication', models.DateField()),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILIA.personne')),
                ('Id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILIA.personne')),
                ('Id_fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.fichier')),
            ],
            options={
                'unique_together': {('Id_Matricule', 'Id_fichier')},
            },
        ),
        migrations.CreateModel(
            name='PersonneProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILIA.personne')),
                ('Id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
            options={
                'unique_together': {('Id_Matricule', 'Id_projet')},
            },
        ),
    ]
