# Generated by Django 5.2.8 on 2025-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projet_createur"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichier",
            name="fichier",
            field=models.FileField(blank=True, null=True, upload_to="projets/"),
        ),
    ]
