# Generated by Django 5.2.8 on 2025-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_fichier_fichier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichier",
            name="fichier",
        ),
        migrations.AddField(
            model_name="fichier",
            name="fichier_contenu",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichier",
            name="fichier_type",
            field=models.CharField(default="application/octet-stream", max_length=100),
        ),
    ]
