# Generated by Django 5.2.8 on 2025-11-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_fichier_fichier_fichier_fichier_contenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='Type',
        ),
        migrations.AddField(
            model_name='fichier',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
