# Generated by Django 5.2.8 on 2025-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_fichier_type_fichier_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='Date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
