# Generated by Django 5.2.8 on 2025-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_fichier_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='Image_projet',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
