# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ILIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('Id_piece', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Etage', models.IntegerField()),
                ('Capacite', models.IntegerField(blank=True, null=True)),
                ('Type', models.IntegerField(choices=[(0, 'Bureau'), (1, 'Salle de réunion'), (2, 'Autre')], default=0)),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['Etage', 'Nom'],
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('Id_bureau', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField(choices=[(0, 'Occupé'), (1, 'Libre'), (2, 'Partageable')], default=1)),
                ('Id_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='reservations.piece')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['Id_piece', 'Id_bureau'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('Id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField(choices=[(0, 'Réunion'), (1, 'Réservation de bureau')], default=1)),
                ('Nom', models.CharField(max_length=100)),
                ('Debut', models.DateTimeField()),
                ('Fin', models.DateTimeField()),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ILIA.personne')),
                ('Id_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.bureau')),
                ('Id_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.piece')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-Debut'],
            },
        ),
        migrations.CreateModel(
            name='PersonneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valide', models.BooleanField(default=False)),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_reservations', to='ILIA.personne')),
                ('Id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Participant à une réservation',
                'verbose_name_plural': 'Participants aux réservations',
                'unique_together': {('Id_Matricule', 'Id_reservation')},
            },
        ),
    ]
