# Generated by Django 5.2.8 on 2025-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Libre'), (1, 'Partageable'), (2, 'Occupé')], default=0),
        ),
    ]
