# Generated by Django 5.2.8 on 2025-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_bureau_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='Nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
