# Generated by Django 5.2.8 on 2025-12-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILIA', '0006_alter_personne_photo'),
        ('reservations', '0003_bureau_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberationBureau',
            fields=[
                ('Id_liberation', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Id_Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberations_bureau', to='ILIA.personne')),
                ('Id_bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberations', to='reservations.bureau')),
            ],
            options={
                'verbose_name': 'Libération de bureau',
                'verbose_name_plural': 'Libérations de bureau',
                'ordering': ['-Date_creation'],
                'unique_together': {('Id_Matricule', 'Id_bureau', 'Date')},
            },
        ),
    ]
