# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=200)),
                ('Contenu', models.TextField()),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('Id_Matricule', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Matricule')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Mot_de_passe', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
                ('Departement', models.CharField(blank=True, max_length=100, null=True)),
                ('Universite', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonneNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_notif', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Id_role', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_role', models.CharField(max_length=100)),
            ],
        ),
    ]
