# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ILIA', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='Id_bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.bureau'),
        ),
        migrations.AddField(
            model_name='personne',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnenotification',
            name='Id_Matricule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILIA.personne'),
        ),
        migrations.AddField(
            model_name='personnenotification',
            name='Id_notif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILIA.notification'),
        ),
        migrations.AddField(
            model_name='personne',
            name='Id_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ILIA.role'),
        ),
        migrations.AddField(
            model_name='personne',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='personnes', to='ILIA.role'),
        ),
        migrations.AlterUniqueTogether(
            name='personnenotification',
            unique_together={('Id_Matricule', 'Id_notif')},
        ),
    ]
