# Generated by Django 5.2.8 on 2025-11-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ILIA", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="Date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="personnenotification",
            name="Date_notif",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
