# Generated by Django 5.2.8 on 2025-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ILIA", "0003_notification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnenotification",
            name="Lu",
            field=models.BooleanField(default=False),
        ),
    ]
