# Generated by Django 5.2.8 on 2025-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILIA', '0004_personnenotification_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo de profil'),
        ),
    ]
