# Generated by Django 5.2.8 on 2025-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILIA', '0005_personne_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='Photo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
